name: Auto Label PR

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequest = context.payload.pull_request;
            
            // Add labels to the PR
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              labels: ['gssoc-ext', 'hacktoberfest-accepted', 'hacktoberfest']
            });
            
            const addLabel = async (label) => {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pullRequest.number,
                labels: [label]
              });
            };
